baseURL = "https://rixycf.github.io/"
languageCode = "en-us"
title = "TEST"
theme = "hugo_theme_pickles"

[params]
  twitter = "sea_ricefield"
  github = "rixycf"
  author = "rixycf"
  bio = "パソコンなんもわからん"

